
// Generated by MaixHub

#ifndef MAIXHUB_MODEL_INFO_H
#define MAIXHUB_MODEL_INFO_H

#define PARAM_VALUE_LAYOUT_HWC 0
#define PARAM_VALUE_LAYOUT_CHW 1

#define PARAM_CLASS_NUM 2
#define PARAM_LABELS {"LZY", "ZHR"}
#define PARAM_MEAN 0
#define PARAM_STD  255
#define PARAM_INPUT_W 224
#define PARAM_INPUT_H 224
#define PARAM_INPUT_C 3
#define PARAM_OUTPUTS_NUM    3
#define PARAM_OUTPUTS_NAMES  {"output0", "output1", "output2"}
#define PARAM_OUTPUTS_VALUES {{28, 28, 21}, {14, 14, 21}, {7, 7, 21}}
#define PARAM_ANCHOR_NUM     9
#define PARAM_ANCHORS        {10, 13, 16, 30, 33, 23, 30, 61, 62, 45, 59, 119, 116, 90, 156, 198, 373, 326}
#define PARAM_OUTPUT_LAYOUT  PARAM_VALUE_LAYOUT_HWC

#endif  // MAIXHUB_MODEL_INFO_H
